import type { Metadata } from "next";
import "../globals.css";
import DesktopNavbar from "@/components/customer/layout/navbar/DesktopNavbar";
import Footer from "@/components/customer/layout/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <DesktopNavbar />
      <main className="flex flex-col items-center justify-center gap-[50px] mx-auto max-w-[1240px]">
        {children}
      </main>
      <Footer />
    </>
  );
}
