import type { Metadata } from "next";
import "../globals.css";
import DesktopNavbar from "@/components/customer/layout/navbar/DesktopNavbar";
import Footer from "@/components/customer/layout/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={` antialiased px-6 md:px-10 xl:px-[100px] py-6 md:py-10`}>
      <DesktopNavbar />
      {children}
      <Footer />
    </div>
  );
}
