export default function Home() {
  return (
    <>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
      <p>dashboard</p>
    </>
  );
}
